# Generated by Django 4.2.30 on 2026-05-08 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryValuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='الكمية')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='تكلفة الوحدة')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='التكلفة الإجمالية')),
                ('method', models.CharField(choices=[('fifo', 'FIFO'), ('average', 'متوسط التكلفة')], default='fifo', max_length=10, verbose_name='طريقة التقييم')),
                ('reference_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع المرجع')),
                ('reference_id', models.IntegerField(blank=True, null=True, verbose_name='رقم المرجع')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuations', to='inventory.batch', verbose_name='الدفعة')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuations', to='inventory.material', verbose_name='الخامة')),
            ],
            options={
                'verbose_name': 'تقييم مخزون',
                'verbose_name_plural': 'تقييم المخزون',
                'ordering': ['-created_at'],
            },
        ),
    ]
