# Generated by Django 4.2.30 on 2026-05-07 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_ar', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'قسم إنتاج',
                'verbose_name_plural': 'أقسام الإنتاج',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('machine_type', models.CharField(choices=[('large_format', 'Large Format'), ('offset', 'Offset'), ('uv', 'UV'), ('sublimation', 'Sublimation'), ('laser', 'Laser'), ('finishing', 'Finishing'), ('other', 'Other')], max_length=20)),
                ('model', models.CharField(blank=True, max_length=200)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('active', 'نشط'), ('maintenance', 'صيانة'), ('inactive', 'غير نشط')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='production.department')),
            ],
            options={
                'verbose_name': 'ماكينة',
                'verbose_name_plural': 'الماكينات',
                'ordering': ['department', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('in_progress', 'قيد التنفيذ'), ('completed', 'مكتمل'), ('quality_check', 'فحص جودة'), ('rejected', 'مرفوض'), ('paused', 'متوقف')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'منخفض'), ('normal', 'عادي'), ('high', 'عالي'), ('urgent', 'عاجل')], default='normal', max_length=20)),
                ('quantity', models.IntegerField()),
                ('completed_quantity', models.IntegerField(default=0)),
                ('rejected_quantity', models.IntegerField(default=0)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('actual_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_tasks', to='employees.employee')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_jobs', to='production.department')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.machine')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_jobs', to='orders.order')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.orderitem')),
            ],
            options={
                'verbose_name': 'أمر إنتاج',
                'verbose_name_plural': 'أوامر الإنتاج',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QualityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_date', models.DateTimeField(auto_now_add=True)),
                ('result', models.CharField(choices=[('passed', 'مقبول'), ('failed', 'مرفوض'), ('conditional', 'معلق بشروط')], max_length=20)),
                ('defects', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('attachments', models.FileField(blank=True, upload_to='quality_checks/')),
                ('checked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
                ('production_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_checks', to='production.productionjob')),
            ],
            options={
                'verbose_name': 'فحص جودة',
                'verbose_name_plural': 'فحوصات الجودة',
                'ordering': ['-check_date'],
            },
        ),
        migrations.CreateModel(
            name='ProductionStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(max_length=200)),
                ('stage_order', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('in_progress', 'قيد التنفيذ'), ('completed', 'مكتمل'), ('skipped', 'تم التجاهل')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee')),
                ('production_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='production.productionjob')),
            ],
            options={
                'verbose_name': 'مرحلة إنتاج',
                'verbose_name_plural': 'مراحل الإنتاج',
                'ordering': ['production_job', 'stage_order'],
            },
        ),
    ]
