# Generated by Django 4.2.30 on 2026-05-07 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='رقم عرض السعر')),
                ('contact_person', models.CharField(blank=True, max_length=200, verbose_name='جهة الاتصال')),
                ('quote_date', models.DateField(auto_now_add=True, verbose_name='تاريخ عرض السعر')),
                ('valid_until', models.DateField(verbose_name='صلاحية حتى')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('sent', 'مرسل'), ('accepted', 'مقبول'), ('rejected', 'مرفوض'), ('expired', 'منتهي'), ('converted', 'محول لطلب')], default='draft', max_length=20, verbose_name='الحالة')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='المجموع الفرعي')),
                ('discount_type', models.CharField(blank=True, choices=[('percentage', 'نسبة مئوية'), ('fixed', 'قيمة ثابتة')], max_length=20, null=True, verbose_name='نوع الخصم')),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='قيمة الخصم')),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=14, max_digits=5, verbose_name='نسبة الضريبة')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='قيمة الضريبة')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الإجمالي')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('terms_conditions', models.TextField(blank=True, verbose_name='الشروط والأحكام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='تم بواسطة')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='customers.customer', verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'عرض سعر',
                'verbose_name_plural': 'عروض الأسعار',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='الوصف')),
                ('quantity', models.IntegerField(verbose_name='الكمية')),
                ('unit', models.CharField(choices=[('piece', 'قطعة'), ('meter', 'متر'), ('sqm', 'متر مربع'), ('roll', 'رول'), ('set', 'طقم'), ('hour', 'ساعة')], default='piece', max_length=20, verbose_name='الوحدة')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='سعر الوحدة')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة الخصم')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الإجمالي')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotes.quote', verbose_name='عرض السعر')),
            ],
            options={
                'verbose_name': 'بند عرض السعر',
                'verbose_name_plural': 'بنود عرض السعر',
            },
        ),
    ]
