# Generated by Django 4.2.30 on 2026-05-07 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('material_unit', 'وحدات القياس'), ('payment_method', 'أنواع الدفع'), ('order_type', 'أنواع الطلبات'), ('machine_type', 'أنواع الماكينات'), ('employee_dept', 'أقسام الموظفين'), ('supplier_type', 'أنواع الموردين'), ('customer_type', 'أنواع العملاء'), ('vat', 'الضرائب')], max_length=30, verbose_name='النوع')),
                ('code', models.CharField(max_length=50, verbose_name='الكود')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='الاسم (إنجليزي)')),
                ('name_ar', models.CharField(max_length=200, verbose_name='الاسم (عربي)')),
                ('sort_order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'إعدادات متقدمة',
                'verbose_name_plural': 'الإعدادات المتقدمة',
                'ordering': ['type', 'sort_order'],
                'unique_together': {('type', 'code')},
            },
        ),
    ]
