# Generated by Django 4.2.30 on 2026-05-07 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_seed_more_lookups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lookup',
            name='type',
            field=models.CharField(choices=[('material_unit', 'وحدات القياس'), ('payment_method', 'أنواع الدفع'), ('order_type', 'أنواع الطلبات'), ('machine_type', 'أنواع الماكينات'), ('employee_dept', 'أقسام الموظفين'), ('supplier_type', 'أنواع الموردين'), ('customer_type', 'أنواع العملاء'), ('vat', 'الضرائب'), ('order_status', 'حالات الطلبات'), ('order_priority', 'أولويات الطلبات'), ('order_item_type', 'أنواع بنود الطلب'), ('order_item_status', 'حالات بنود الطلب'), ('unit', 'وحدات القياس'), ('discount_type', 'أنواع الخصم'), ('delivery_note_status', 'حالات مذكرات التسليم'), ('production_job_status', 'حالات أوامر الإنتاج'), ('production_stage_status', 'حالات مراحل الإنتاج'), ('quality_check_result', 'نتائج فحص الجودة'), ('machine_status', 'حالات الماكينات'), ('quote_status', 'حالات عروض الأسعار'), ('stock_movement_type', 'أنواع الحركات المخزنية'), ('pos_session_status', 'حالات جلسات البيع'), ('pos_sale_status', 'حالات فواتير البيع'), ('pos_item_type', 'أنواع بنود الفواتير'), ('purchase_order_status', 'حالات أوامر الشراء'), ('interaction_type', 'أنواع التفاعلات'), ('customer_payment_method', 'طرق دفع العملاء'), ('leave_type', 'أنواع الإجازات'), ('leave_status', 'حالات الإجازات'), ('attendance_status', 'حالات الحضور'), ('employee_salary_type', 'أنواع الرواتب')], max_length=30, verbose_name='النوع'),
        ),
    ]
