# Generated by Django 4.2.30 on 2026-05-07 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quotes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='رقم الطلب')),
                ('order_type', models.CharField(choices=[('normal', 'عادي'), ('urgent', 'مستعجل'), ('pos', 'نقطة بيع')], default='normal', max_length=20, verbose_name='نوع الطلب')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('delivery_date', models.DateField(verbose_name='تاريخ التسليم')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('confirmed', 'مؤكد'), ('in_design', 'في التصميم'), ('in_production', 'في الإنتاج'), ('in_finishing', 'في التشطيب'), ('quality_check', 'فحص الجودة'), ('ready', 'جاهز'), ('delivered', 'تم التسليم'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='الحالة')),
                ('priority', models.CharField(choices=[('low', 'منخفض'), ('normal', 'عادي'), ('high', 'عالي'), ('urgent', 'عاجل')], default='normal', max_length=20, verbose_name='الأولوية')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='المجموع الفرعي')),
                ('discount_type', models.CharField(blank=True, choices=[('percentage', 'نسبة مئوية'), ('fixed', 'قيمة ثابتة')], max_length=20, null=True, verbose_name='نوع الخصم')),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='قيمة الخصم')),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=14, max_digits=5, verbose_name='نسبة الضريبة')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='قيمة الضريبة')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='تكلفة الشحن')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الإجمالي')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='المبلغ المدفوع')),
                ('due_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='المبلغ المتبقي')),
                ('payment_status', models.CharField(choices=[('unpaid', 'غير مدفوع'), ('partial', 'مدفوع جزئياً'), ('paid', 'مدفوع بالكامل')], default='unpaid', max_length=20, verbose_name='حالة الدفع')),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'نقدي'), ('bank', 'تحويل بنكي'), ('cheque', 'شيك'), ('credit', 'بطاقة ائتمان'), ('later', 'آجل')], max_length=20, null=True, verbose_name='طريقة الدفع')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('internal_notes', models.TextField(blank=True, verbose_name='ملاحظات داخلية')),
                ('delivery_address', models.TextField(blank=True, verbose_name='عنوان التسليم')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='تم بواسطة')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='customers.customer', verbose_name='العميل')),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='quotes.quote', verbose_name='عرض السعر')),
            ],
            options={
                'verbose_name': 'طلب',
                'verbose_name_plural': 'الطلبات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ')),
                ('payment_date', models.DateField(auto_now_add=True, verbose_name='تاريخ الدفع')),
                ('payment_method', models.CharField(choices=[('cash', 'نقدي'), ('bank', 'تحويل بنكي'), ('cheque', 'شيك'), ('credit', 'بطاقة ائتمان')], default='cash', max_length=20, verbose_name='طريقة الدفع')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='مرجع')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='تم بواسطة')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'دفعة',
                'verbose_name_plural': 'المدفوعات',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('printing', 'طباعة'), ('laser', 'ليزر'), ('engraving', 'حفر'), ('design', 'تصميم'), ('material', 'خامات'), ('other', 'أخرى')], default='printing', max_length=20, verbose_name='نوع البند')),
                ('description', models.CharField(max_length=500, verbose_name='الوصف')),
                ('design_file', models.FileField(blank=True, upload_to='designs/', verbose_name='ملف التصميم')),
                ('quantity', models.IntegerField(verbose_name='الكمية')),
                ('unit', models.CharField(choices=[('piece', 'قطعة'), ('meter', 'متر'), ('sqm', 'متر مربع'), ('roll', 'رول'), ('set', 'طقم'), ('hour', 'ساعة')], default='piece', max_length=20, verbose_name='الوحدة')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='سعر الوحدة')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة الخصم')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الإجمالي')),
                ('production_notes', models.TextField(blank=True, verbose_name='ملاحظات الإنتاج')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('in_design', 'في التصميم'), ('in_production', 'في الإنتاج'), ('in_finishing', 'في التشطيب'), ('completed', 'مكتمل')], default='pending', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee', verbose_name='مسند إلى')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'بند الطلب',
                'verbose_name_plural': 'بنود الطلب',
            },
        ),
        migrations.CreateModel(
            name='DesignFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='designs/%Y/%m/', verbose_name='الملف')),
                ('version', models.IntegerField(default=1, verbose_name='الإصدار')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_files', to='orders.order', verbose_name='الطلب')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='تم الرفع بواسطة')),
            ],
            options={
                'verbose_name': 'ملف تصميم',
                'verbose_name_plural': 'ملفات التصميم',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivered_by', models.CharField(max_length=200, verbose_name='تم التسليم بواسطة')),
                ('received_by', models.CharField(blank=True, max_length=200, verbose_name='استلم')),
                ('delivery_date', models.DateTimeField(verbose_name='تاريخ التسليم')),
                ('items_delivered', models.TextField(verbose_name='البنود المسلمة')),
                ('status', models.CharField(choices=[('partial', 'تسليم جزئي'), ('full', 'تسليم كامل')], default='full', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_notes', to='orders.order', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'مذكرة تسليم',
                'verbose_name_plural': 'مذكرات التسليم',
                'ordering': ['-delivery_date'],
            },
        ),
    ]
