# Generated by Django 4.2.30 on 2026-05-07 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'قيد الانتظار'), ('in_design', 'في التصميم'), ('in_production', 'في الإنتاج'), ('in_finishing', 'في التشطيب'), ('completed', 'مكتمل')], default='pending', max_length=20, verbose_name='الحالة'),
        ),
    ]
