# Generated by Django 4.2.30 on 2026-05-08 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitem_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpayment',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الدفع'),
        ),
    ]
