# Generated by Django 4.2.30 on 2026-05-08 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_assign_admin_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='client_discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة خصم العميل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'مدير النظام'), ('manager', 'مدير'), ('supervisor', 'مشرف'), ('cashier', 'كاشير'), ('staff', 'موظف'), ('client', 'عميل')], default='staff', max_length=20, verbose_name='الدور'),
        ),
    ]
