# Generated by Django 4.2.30 on 2026-05-07 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(max_length=20, unique=True, verbose_name='كود الموظف')),
                ('full_name', models.CharField(max_length=200, verbose_name='الاسم الكامل')),
                ('full_name_ar', models.CharField(blank=True, max_length=200, verbose_name='الاسم بالعربية')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('position', models.CharField(max_length=200, verbose_name='المسمى الوظيفي')),
                ('department', models.CharField(choices=[('management', 'إدارة'), ('design', 'تصميم'), ('printing', 'طباعة'), ('finishing', 'تشطيب'), ('sales', 'مبيعات'), ('warehouse', 'مخزن'), ('delivery', 'توصيل')], max_length=50, verbose_name='القسم')),
                ('hire_date', models.DateField(verbose_name='تاريخ التعيين')),
                ('salary_type', models.CharField(choices=[('fixed', 'ثابت'), ('hourly', 'بالساعة'), ('commission_based', 'عمولة')], max_length=50, verbose_name='نوع الراتب')),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الراتب الأساسي')),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة العمولة')),
                ('id_number', models.CharField(blank=True, max_length=50, verbose_name='رقم الهوية')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('emergency_contact', models.CharField(blank=True, max_length=200, verbose_name='جهة اتصال طارئة')),
                ('emergency_phone', models.CharField(blank=True, max_length=20, verbose_name='هاتف الطوارئ')),
                ('bank_account', models.CharField(blank=True, max_length=100, verbose_name='الحساب البنكي')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('photo', models.ImageField(blank=True, upload_to='employees/', verbose_name='صورة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'موظف',
                'verbose_name_plural': 'الموظفين',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('annual', 'سنوية'), ('sick', 'مرضية'), ('emergency', 'طارئة'), ('unpaid', 'بدون راتب')], max_length=20, verbose_name='نوع الإجازة')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ النهاية')),
                ('days_count', models.IntegerField(verbose_name='عدد الأيام')),
                ('reason', models.TextField(verbose_name='السبب')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('approved', 'معتمدة'), ('rejected', 'مرفوضة')], default='pending', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to=settings.AUTH_USER_MODEL, verbose_name='معتمد بواسطة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='employees.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'إجازة',
                'verbose_name_plural': 'الإجازات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('reason', models.TextField(blank=True, verbose_name='السبب')),
                ('repaid', models.BooleanField(default=False, verbose_name='تم السداد')),
                ('repayment_date', models.DateField(blank=True, null=True, verbose_name='تاريخ السداد')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advances', to='employees.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'سلفة',
                'verbose_name_plural': 'السلف',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=7, verbose_name='الشهر (YYYY-MM)')),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الراتب الأساسي')),
                ('bonuses', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المكافآت')),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الخصومات')),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='العمولة')),
                ('overtime', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الإضافي')),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='صافي الراتب')),
                ('paid', models.BooleanField(default=False, verbose_name='تم الدفع')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الدفع')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='employees.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'راتب',
                'verbose_name_plural': 'الرواتب',
                'ordering': ['-month'],
                'unique_together': {('employee', 'month')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('check_in', models.TimeField(verbose_name='وقت الحضور')),
                ('check_out', models.TimeField(blank=True, null=True, verbose_name='وقت الانصراف')),
                ('status', models.CharField(choices=[('present', 'حاضر'), ('absent', 'غائب'), ('late', 'متأخر'), ('half_day', 'نصف يوم'), ('holiday', 'إجازة رسمية'), ('leave', 'إجازة')], max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='employees.employee', verbose_name='الموظف')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='مسجل بواسطة')),
            ],
            options={
                'verbose_name': 'حضور',
                'verbose_name_plural': 'الحضور والانصراف',
                'ordering': ['-date', '-check_in'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
