# Generated by Django 4.2.30 on 2026-05-08 03:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculatorQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=200, verbose_name='اسم جهة الاتصال')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('contact_phone', models.CharField(max_length=50, verbose_name='رقم الهاتف')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='الشركة')),
                ('quote_number', models.CharField(max_length=50, unique=True, verbose_name='رقم عرض السعر')),
                ('quote_type', models.CharField(choices=[('printing', 'طباعة'), ('giveaway', 'هدايا دعائية'), ('mixed', 'مختلط')], default='printing', max_length=20, verbose_name='النوع')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='المجموع الفرعي')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة الخصم')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='قيمة الخصم')),
                ('tax_percent', models.DecimalField(decimal_places=2, default=14, max_digits=5, verbose_name='نسبة الضريبة')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='قيمة الضريبة')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الإجمالي')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('submitted', 'مُرسل'), ('approved', 'مقبول'), ('rejected', 'مرفوض')], default='draft', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calculator_quotes', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'عرض سعر عميل',
                'verbose_name_plural': 'عروض أسعار العملاء',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GiveawayCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم (إنجليزي)')),
                ('name_ar', models.CharField(max_length=200, verbose_name='الاسم (عربي)')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('icon', models.CharField(blank=True, help_text='Bootstrap icon class', max_length=50, verbose_name='الأيقونة')),
                ('sort_order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'تصنيف هدية دعائية',
                'verbose_name_plural': 'تصنيفات الهدايا الدعائية',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GiveawayOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم (إنجليزي)')),
                ('name_ar', models.CharField(max_length=200, verbose_name='الاسم (عربي)')),
                ('price_adjustment', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='تعديل السعر')),
                ('sort_order', models.IntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'خيار إضافي',
                'verbose_name_plural': 'الخيارات الإضافية',
                'ordering': ['product', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم (إنجليزي)')),
                ('name_ar', models.CharField(max_length=200, verbose_name='الاسم (عربي)')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('icon', models.CharField(blank=True, help_text='Bootstrap icon class', max_length=50, verbose_name='الأيقونة')),
                ('sort_order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'تصنيف خدمة طباعة',
                'verbose_name_plural': 'تصنيفات خدمات الطباعة',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم (إنجليزي)')),
                ('name_ar', models.CharField(max_length=200, verbose_name='الاسم (عربي)')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('image', models.ImageField(blank=True, null=True, upload_to='calculator/services/', verbose_name='الصورة')),
                ('has_options', models.BooleanField(default=False, verbose_name='له خيارات إضافية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='calculator.servicecategory', verbose_name='التصنيف')),
            ],
            options={
                'verbose_name': 'منتج طباعة',
                'verbose_name_plural': 'منتجات الطباعة',
                'ordering': ['category__sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PricingTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_from', models.IntegerField(verbose_name='الكمية من')),
                ('qty_to', models.IntegerField(verbose_name='الكمية إلى')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الوحدة')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_tiers', to='calculator.serviceproduct', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'شريحة سعرية (طباعة)',
                'verbose_name_plural': 'الشرائح السعرية (طباعة)',
                'ordering': ['product', 'qty_from'],
            },
        ),
        migrations.CreateModel(
            name='GiveawayProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم (إنجليزي)')),
                ('name_ar', models.CharField(max_length=200, verbose_name='الاسم (عربي)')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('image', models.ImageField(blank=True, null=True, upload_to='calculator/giveaways/', verbose_name='الصورة')),
                ('has_options', models.BooleanField(default=False, verbose_name='له خيارات إضافية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='calculator.giveawaycategory', verbose_name='التصنيف')),
            ],
            options={
                'verbose_name': 'هدية دعائية',
                'verbose_name_plural': 'الهدايا الدعائية',
                'ordering': ['category__sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GiveawayPricingTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_from', models.IntegerField(verbose_name='الكمية من')),
                ('qty_to', models.IntegerField(verbose_name='الكمية إلى')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الوحدة')),
                ('option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pricing_tiers', to='calculator.giveawayoption', verbose_name='الخيار')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_tiers', to='calculator.giveawayproduct', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'شريحة سعرية (هدية)',
                'verbose_name_plural': 'الشرائح السعرية (هدية)',
                'ordering': ['product', 'qty_from'],
            },
        ),
        migrations.AddField(
            model_name='giveawayoption',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='calculator.giveawayproduct', verbose_name='المنتج'),
        ),
        migrations.CreateModel(
            name='CalculatorQuoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('service', 'خدمة طباعة'), ('giveaway', 'هدية دعائية')], max_length=20, verbose_name='نوع المنتج')),
                ('category_name', models.CharField(max_length=200, verbose_name='اسم التصنيف')),
                ('product_name', models.CharField(max_length=200, verbose_name='اسم المنتج')),
                ('option_name', models.CharField(blank=True, max_length=200, verbose_name='الخيار')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='الكمية')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الوحدة')),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='الإجمالي')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='calculator.calculatorquote', verbose_name='عرض السعر')),
            ],
            options={
                'verbose_name': 'بند عرض سعر عميل',
                'verbose_name_plural': 'بنود عروض أسعار العملاء',
            },
        ),
    ]
