# Generated by Django 4.2.30 on 2026-05-07 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.CharField(blank=True, help_text='الاسم الأساسي للعميل (اسم الشخص للفرد، أو اسم الشركة للشركة)', max_length=200, verbose_name='الاسم'),
        ),
    ]
