# Generated by Django 4.2.30 on 2026-05-08 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventoryvaluation'),
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='possaleitem',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.material', verbose_name='الخامة'),
        ),
    ]
